#!/bin/bash

kubermachines() {
   
    if [[ $1 == "configure" ]]; then 

	if [[ $2 == "-f" ]]; then
	     
             if [[ -n $3 ]]; then 
                export CONTEXT_FILE=$3
	        curl -fsSL https://raw.githubusercontent.com/Kubermachines2020/Spaces/main/configure.sh  | bash

	     elif [[ -z $3 ]]; then
	        echo -e "Context file path is missing."		
	     fi


	elif [[ -z $2 ]]; then
             export CONTEXT_FILE="contextfile.yml"
             curl -fsSL https://raw.githubusercontent.com/Kubermachines2020/Spaces/main/configure.sh  | bash

	elif [[ -n $2 ]]; then
	     echo -e "'$2' is not a kubermachines $1 option. See 'kubermachines help' for usage."
        fi

    elif [[ $@ == "up" ]]; then
        tilt up
    
    elif [[ $@ == "down" ]]; then
        tilt down
     
    elif [[ $@ == "help" ]]; then
        echo -e "Run 'kubermachines up' to deploy your services in a development space configured for your team.\nUsage: kubermachines COMMAND\n\nAvailable commands:\ninstall     Install dependencies\nconfigure   Set your services configurations\nup          Start Kubermachines with the given Tiltfile args\ndown        Delete resources created by 'kubermachines up'\n"

    else 
	    echo -e "kubermachines: '$@' is not a kubermachines command.\nSee 'kubermachines help' for usage."
    fi
}
